version: '3.7'

services:
  app:
    build: .
    image: simple_billing
    entrypoint: >
      sh -c './wait-for-it.sh -t 10 postgres:5432
      && python main.py'
#    entrypoint: sh -c 'while true; do echo "working..."; sleep 60; done'
    volumes:
      - ./:/usr/src/app/
      - ./utils/wait-for-it.sh:/usr/src/app/wait-for-it.sh:cached
    depends_on:
      - postgres
    ports:
    - "8080:8080"

  functional_tests:
    image: simple_billing
    entrypoint: >
      sh -c './wait-for-it.sh -t 10 app:8080
      && sleep 5
      && pytest tests'
#    entrypoint: sh -c 'while true; do echo "working..."; sleep 60; done'
    volumes:
      - ./:/usr/src/app/
      - ./utils/wait-for-it.sh:/usr/src/app/wait-for-it.sh:cached
    depends_on:
      - app

  postgres:
    image: postgres:13
    volumes:
      - ./migrations/sql:/docker-entrypoint-initdb.d/migrations-1
      - ./migrations/pg_init.sh:/docker-entrypoint-initdb.d/pg_init.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: billing

  pgweb:
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/billing?sslmode=disable
    depends_on:
      - postgres
