openapi: "3.0.0"
info:
  version: 1.0.0
  title: Simple Billing API
  description: "API простого биллинга"

paths:
  /billing/v1/create_wallet:
    post:
      summary: Создание кошелька для пользователя (существующего в другой системе)
      parameters:
        - in: header
          name: X-Signature
          description: "hmac-имитовставка"
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWalletRequest'
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateWalletResponse'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /billing/v1/wallet_credit:
    post:
      summary: Зачисление средств на кошелёк
      parameters:
        - in: header
          name: X-Signature
          description: "hmac-имитовставка"
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletCreditRequest'
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletCreditResponse'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /billing/v1/wallet_debit:
    post:
      summary: Списание денег с кошелька
      parameters:
        - in: header
          name: X-Signature
          description: "hmac-имитовставка"
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletDebitRequest'
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletDebitResponse'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /billing/v1/wallet_p2p_transfer:
    post:
      summary: Перевод на другой кошелёк
      parameters:
        - in: header
          name: X-Signature
          description: "hmac-имитовставка"
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletP2PTransferRequest'
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletP2PTransferResponse'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    CreateWalletRequest:
      required:
        - operation_id
        - user_id
      properties:
        operation_id:
          description: "Идентификатор операции. Метод идемпотентный, при повторной отправке запроса с идентичным operation_id новый процесс создания кошелька запущен не будет"
          type: string
        user_id:
          description: "Идентификатор пользователя"
          type: integer

    CreateWalletResponse:
      required:
        - operation_id
        - code
        - message
      properties:
        operation_id:
          description: "Идентификатор операции"
          type: string
        code:
          description: >
            Код ответа.
              *  0 - Метод выполнен успешно
              *  101 - Неверный формат данных (пропущены необходимые поля)
              *  201 - Кошелёк для пользователя с таким user_id уже существует
          type: integer
          enum: [0, 101, 201]
        wallet_id:
          description: "Идентификатор кошелька"
          type: string
        message:
          description: "Сообщение ответа"
          type: string

    WalletCreditRequest:
      required:
        - operation_id
        - wallet_id
        - amount
      properties:
        operation_id:
          description: "Идентификатор операции. Метод идемпотентный, при повторной отправке запроса с идентичным operation_id новый процесс создания кошелька запущен не будет"
          type: string
        wallet_id:
          description: "Идентификатор кошелька"
          type: string
        amount:
          description: "Сумма в центах"
          type: integer

    WalletCreditResponse:
      required:
        - operation_id
        - code
        - message
      properties:
        operation_id:
          description: "Идентификатор операции"
          type: string
        code:
          description: >
            Код ответа.
              *  0 - Метод выполнен успешно
              *  101 - Неверный формат данных (пропущены необходимые поля)
              *  202 - Кошелёк не найден
          type: integer
          enum: [0, 101, 201]
        message:
          description: "Сообщение ответа"
          type: string

    WalletDebitRequest:
      required:
        - operation_id
        - wallet_id
        - amount
      properties:
        operation_id:
          description: "Идентификатор операции. Метод идемпотентный, при повторной отправке запроса с идентичным operation_id новый процесс создания кошелька запущен не будет"
          type: string
        wallet_id:
          description: "Идентификатор кошелька"
          type: string
        amount:
          description: "Сумма в центах"
          type: integer

    WalletDebitResponse:
      required:
        - operation_id
        - code
        - message
      properties:
        operation_id:
          description: "Идентификатор операции"
          type: string
        code:
          description: >
            Код ответа.
              *  0 - Метод выполнен успешно
              *  101 - Неверный формат данных (пропущены необходимые поля)
              *  201 - Кошелёк не найден
              *  202 - Недостаточно средств
          type: integer
          enum: [0, 101, 201, 202]
        message:
          description: "Сообщение ответа"
          type: string

    WalletP2PTransferRequest:
      required:
        - operation_id
        - from_wallet_id
        - to_wallet_id
        - amount
      properties:
        operation_id:
          description: "Идентификатор операции. Метод идемпотентный, при повторной отправке запроса с идентичным operation_id новый процесс создания кошелька запущен не будет"
          type: string
        from_wallet_id:
          description: "Идентификатор кошелька отправителя"
          type: string
        to_wallet_id:
          description: "Идентификатор кошелька получателя"
          type: string
        amount:
          description: "Сумма в центах"
          type: integer

    WalletP2PTransferResponse:
      required:
        - operation_id
        - code
        - message
      properties:
        operation_id:
          description: "Идентификатор операции"
          type: string
        code:
          description: >
            Код ответа.
              *  0 - Метод выполнен успешно
              *  101 - Неверный формат данных (пропущены необходимые поля)
              *  201 - Кошелёк не найден
              *  202 - Недостаточно средств
          type: integer
          enum: [0, 101, 201, 202]
        message:
          description: "Сообщение ответа"
          type: string

    Error:
      type: object
      description: "Схема сообщения об ошибке обработки запроса"
      properties:
        error:
          type: object
          properties:
            code:
              description: "Код ошибки"
              type: integer
            message:
              description: "Описание ошибки"
              type: string

  responses:
    Forbidden:
      description: "Ошибка при проверке подписи"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error:
              code: 403
              message: "Wrong signature"
    InternalServerError:
      description: "Ошибка на сервере"
